apiVersion: v1
kind: ConfigMap
metadata:
  name: bw-db-config
  namespace: default
data:
  API_WHITELIST_IP: "127.0.0.0/24 10.0.0.0/8 192.168.0.0/24"
  DATABASE_URI: "mariadb+pymysql://bunkerweb:changeme@127.0.0.1:3306/db"
  MYSQL_RANDOM_ROOT_PASSWORD: "yes"
  MYSQL_DATABASE: "db"
  MYSQL_USER: "bunkerweb"
  MYSQL_PASSWORD: "changeme"
  LOG_LEVEL: "debug"
  UI_LISTEN_ADDR: "0.0.0.0"
  UI_LISTEN_PORT: "7000"
  DNS_RESOLVERS: "kube-dns.kube-system.svc.cluster.local"
