apiVersion: apps/v1
kind: Deployment
metadata:
  name: borg-web-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: borg-web-ui
  template:
    metadata:
      labels:
        app: borg-web-ui
    spec:
      containers:
        - name: borg-web-ui
          image: ainullcode/borg-ui:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
              hostPort: 8002
          env:
            - name: PORT
              value: "8081"
            - name: PUID
              value: "1001"
            - name: PGID
              value: "1001"
            - name: TZ
              value: "UTC"
            - name: LOCAL_MOUNT_POINTS
              value: "/local"
            - name: REDIS_HOST
              value: "disabled"
          volumeMounts:
            - name: borg-data
              mountPath: /data
            - name: borg-cache
              mountPath: /home/borg/.cache/borg
            - name: local-storage
              mountPath: /local
            - name: localtime
              mountPath: /etc/localtime
              readOnly: true
      volumes:
        - name: borg-data
          persistentVolumeClaim:
            claimName: borg-data-pvc
        - name: borg-cache
          persistentVolumeClaim:
            claimName: borg-cache-pvc
        - name: local-storage
          hostPath:
            path: /mnt/local/borg-backup
            type: Directory
        - name: localtime
          hostPath:
            path: /etc/localtime
            type: File
