apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-vw-data
spec:
  storageClassName: pv-vw-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vw-data
  labels:
    type: local
spec:
  storageClassName: pv-vw-data
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/drive-tmp/vaultwarden/data/"
