- name: Install nftables
  ansible.builtin.apt:
    name: nftables
    state: present
    update_cache: yes
  become: true

- name: Enable ip forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present
    sysctl_set: true
  become: true

- name: Write firewall configuration to nftables
  ansible.builtin.blockinfile:
    path: /etc/nftables.conf
    block: |
      #!/usr/sbin/nft -f

      flush ruleset

      table inet filter {
        chain input {
          type filter hook input priority filter;
          ct state established,related accept
          accept
        }
        chain forward {
          type filter hook forward priority filter;
          ct state established,related accept
          accept
        }
        chain output {
          type filter hook output priority filter;
          ct state established,related accept
          accept
        }
      }

      table inet nat {
        chain postrouting {
          type nat hook postrouting priority 100;
          oifname wlo1 masquerade
          accept
        }
        chain prerouting {
          type nat hook prerouting priority -100;
          # dNAT port forwarding for the authentik server
          iifname wlo1 tcp dport 8043 dnat ip to 192.168.50.173:443
          iifname wlo1 tcp dport 8080 dnat ip to 192.168.50.173:80
          accept
        }
      }
    marker: "# --- {mark} ANSIBLE MANAGED BLOCK ---"

- name: Reload firewall
  ansible.builtin.shell: | 
    systemctl stop iptables
    systemctl disable iptables
    systemctl enable nftables
    systemctl restart nftables
  become: true

