apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-joplin-db-data
spec:
  storageClassName: pv-joplin-db-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
