apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-caddy-conf
spec:
  storageClassName: pv-caddy-conf
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-caddy-site
spec:
  storageClassName: pv-caddy-site
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-caddy-data
spec:
  storageClassName: pv-caddy-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-caddy-config
spec:
  storageClassName: pv-caddy-config
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
