apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vw-data
  labels:
    type: local
spec:
  storageClassName: pv-vw-data
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/root/vaultwarden/data/"
