apiVersion: v1
kind: PersistentVolume
metadata:
  name: bunkerweb-volume
  labels:
    type: local
spec:
  storageClassName: rp
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

